galaxy_info:
  author: daos-stack
  description: Role to tune system parameters
  company: Intel Corporation
  issue_tracker_url: https://daosio.atlassian.net/jira

  license: Apache-2.0

  min_ansible_version: "2.11"

  platforms:
    - name: EL
      versions:
        - "8"

galaxy_tags:
  - system
  - daos

dependencies: []
